.Dd January 17, 2026
.Dt LABELGREP 1
.Os
.Sh NAME
.Nm labelgrep
.Nd progressive label file searcher
.Sh SYNOPSIS
.Nm labelgrep
.Ar pattern
.Ar file
.Op Ar file ...
.Sh DESCRIPTION
A pattern searcher for the
.Xr pln 5
format.
Displays the source file, label name, and highlights the contents matching a
regular expression.
.Pp
Lines beginning with
.Ql \&#
are ignored.
.Sh EXAMPLES
Find all of the instances where a service is restarted
.Pp
.Dl labelgrep 'rcctl|systemctl' *.pln
.Pp
Show all routes that include the wordpress configuration
.Pp
.Dl labelgrep 'wordpress' routes.pln
.Sh SEE ALSO
.Xr rset 1 ,
.Xr re_format 7
.Sh HISTORY
The
.Nm
utility was introduced in rset 1.2
.Sh CAVEATS
.Nm
does not attempt to validate the format of each file.
