.Dd January 17, 2026
.Dt MINIQUARK 1
.Os
.Sh NAME
.Nm miniquark
.Nd a minimal web server for retrieving files
.Sh SYNOPSIS
.Nm
.Op Fl d Ar dir
.Op Fl l Ar address
.Ar port
.Sh DESCRIPTION
.Nm
is a web server supporting GET/HEAD requests and is easily launched as
unprivileged user to provide HTTP access a local directory.
.Pp
The options are as follows:
.Bl -tag -width 8n
.It Fl d Ar dir
Switch to the specified directory.
.It Fl l Ar address
Set the hostname or IP address to listen on.
The default is
.Ql localhost .
.El
.Pp
.Ar port
is required, and specifies the TCP port number for incoming connections.
.Sh FEATURES
The following request headers are recognized
.Bl -tag -width 0n
.It Range:
Returns 206 Partial Content and the Content-Range header is set.
.It If-Modified-Since:
Returns 304 Not Modified or "200 OK" based on the file timestamp.
.It User-Agent:
Used for log messages.
.El
.Sh HISTORY
.Nm
was based on
.Lk https://git.suckless.org/quark
and bundled with
.Xr rset 1
in July 2020.
