.Dd August 3, 2026
.Dt PLN 5
.Os
.Sh NAME
.Nm pln
.Nd progressive label notation
.Sh DESCRIPTION
Progressive Label Notation
is a configuration format used by
.Xr rset 1 .
.Nm
allows key-value options to be defined inline, and tab-indented code blocks
called
.Em labels
to be executed sequentially.
Labels support a single type of annotation known as
.Em export paths .
.Pp
.Nm
files are arranged in a two-level hierarchy: a top-level routes file maps
hostnames to a list of .pln files.
All .pln files included in a route label are expected to be executed within a
single
.Em session .
.Sh OPTIONS
Options may be set multiple times, and are effective for subsequent labels.
The value is assigned all text between first `=` character and
.Aq newline
.Bd -literal -offset indent
environment=LC_ALL="C.UTF-8"
.Ed
.Pp
An name ending with `=` is an empty assignment and will reset the option to a
default value.
.Sh ROUTE LABELS
Labels may be split into multiple aliases separated by commas
.Bd -literal -offset indent
svc1,10.0.0.10:
	common.pln
	svc.pln
.Ed
.Pp
Alternatively, sequence expressions may be used to define a host range
.Bd -literal -offset indent
fs{2..5}.lan:
	zpool.pln
.Ed
.Pp
A list of pathnames following
.Ql \&:
indicate directories to be staged on the remote host
.Bd -literal -offset indent
scriptedconfiguration.org: common/ hub/
	users.pln
	hub.pln
.Ed
.Sh HOST LABELS
Content defined between
.Aq tab
and
.Aq newline
is piped verbatim to external commands, avoiding the need to escape special
characters.
Empty lines are also permitted
.Bd -literal -offset indent
packages:
	echo "http://cdn.openbsd.org/pub/OpenBSD" > /etc/installurl
	pkg_add rsync--

	mkdir -p /tftpboot/efi
.Ed
.Pp
A pair of braces immediately following a label captures the output of local
execution before initiating a remote connection.
The result of local execution is concatenated with the label content to form
single script
.Bd -literal -offset indent
set date:
{
	echo "NOW=$(date +%Y%m%d%H%M)"
}
	date $NOW
.Ed
.Pp
In specialized cases, export paths following
.Ql \&:
identifies files to send or retrieve
.Bd -literal -offset indent
_archive: hub.tar
	tar -Pp -cf hub.tar /var/www /etc/ssl
.Ed
.Sh COMMENTS
Comments begin with
.Ql \&# ,
and are only recognized at start of a line.
.Sh SEE ALSO
.Xr labelgrep 1
.Sh AUTHORS
.An Eric Radman Aq Mt ericshane@eradman.com
