.\"
.\" Copyright (c) 2023 Eric Radman <ericshane@eradman.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd November 25, 2023
.Dt RENV 1
.Os
.Sh NAME
.Nm renv
.Nd normalize environment variables
.Sh SYNOPSIS
.Nm renv
.Ar file ...
.Nm renv
.Ar name="value" Op file
.Sh DESCRIPTION
Filter environment variables in a format suitable for
.Xr sh 1 .
Only lines defining variable names using the characters
.Bq _a-zA-Z0-9
with a value in double-quotes are emitted.
Values may also be empty.
.Pp
.Dl A="one"
.Dl B="two"
.Dl D=""
.Pp
If the first argument is in the format
.Ql name=value
.Nm
will store and environment for reference in subsequent labels.
By default entries are appended to
.Pa $SD/local.env .
.Sh LITERALS
Escape sequences starting with
.Sq \e ,
or subshells using
.Sq $(...)
are not permitted.
.Pp
.Ql \&$$
expands to a single dollar sign.
.Sh EXAMPLES
Print environment variables in a normalized format
.Pp
.Dl $ renv final.env
.Pp
Save the status code of the last command
.Pp
.Dl $ renv LAST_EXITSTATUS="$?"
.Sh SEE ALSO
.Xr rset 1
.Sh CAVEATS
Tabs and multiple spaces are converted to into a single space.
There is no provision for embedding literal double-quotes.
.Pp
.Nm
must be found in the current working directory or in the path defined by
.Ev SD .
