.\"
.\" Copyright (c) 2018 Eric Radman <ericshane@eradman.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd December 7, 2023
.Dt RINSTALL 1
.Os
.Sh NAME
.Nm rinstall
.Nd fetch and install scripts from local or http source
.Sh SYNOPSIS
.Nm rinstall
.Op Fl a Ar URL
.Op Fl m Ar mode
.Op Fl o Ar owner:group
.Ar source
.Op Ar target
.Sh DESCRIPTION
.Nm
is shipped to remote machines by
.Xr rset 1
to provide a standard method of installing files made available over HTTP, or
from the current working directory for files already staged.
.Pp
The
.Ar target
must be an absolute path, and is created if it does not exist.
If the
.Ar target
exists but is not the same as
.Ar source ,
then
.Xr diff 1
is used to display the difference before it is updated.
.Pp
If the
.Ar target
is omitted, the
.Ar source
is placed in the staging directory defined by the
.Ev SD
environment variable.
The source may be defined with either an absolute or relative path.
An absolute path points to a file on a local file system on the remote side.
Although, if the source is defined with a relative path, then
.Nm
first checks if the source already exists in the
.Ev SD
and then tries to fetch it from the HTTP resource defined by
.Ev INSTALL_URL
or the
.Fl a
option.
.Pp
.Nm
always checks for a local copy of the
.Ar source
before attempting to fetch a file from the location defined by the environment
variable
.Ev INSTALL_URL .
.Pp
The arguments are as follows:
.Bl -tag -width Ds
.It Fl a
URL to an alternative file location.
.It Fl m
Mode to set when a file is updated.
This argument is passed to
.Xr chmod 1 .
.It Fl o
Owner and/or group to set.
This argument is passed to
.Xr chown 1 .
.El
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev RINSTALL_DIFF_ARGS
Arguments for
.Xr diff 1
tool.
Default is "-U 2"
.El
.Sh EXIT STATUS
The
.Nm
utility exits with one of the following values:
.Pp
.Bl -tag -width Ds -offset indent -compact
.It 0
Target file was installed or updated
.It 1
No changes were made
.It 2
Unknown Operating System
.It 3
Unable to fetch requested file
.El
.Sh EXAMPLES
Install configuration file and set permissions
.Pp
.Dl $SD/rinstall -m 644 -o www:www resolv.conf /var/www/etc/
.Pp
Fetch latest copy of sources and extract
.Pp
.Dl $SD/rinstall wodpress.tar.gz
.Dl tar -xzf $SD/wordpress.tar.gz -C /var/www
.Pp
Fetch a file from an alternative location and store it in the Staging Directory
under tools/sys/ if it's not already there and it's not available at
$INSTALL_URL/tools/sys/sometool.tgz
.Pp
.Dl $SD/rinstall -a https://example.org/files/tool.tar.gz tools/sys/sometool.tgz
