.\"
.\" Copyright (c) 2018 Eric Radman <ericshane@eradman.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd November 3, 2023
.Dt RSET 1
.Os
.Sh NAME
.Nm rset
.Nd remote staging and execution tool
.Sh SYNOPSIS
.Nm rset
.Op Fl elntv
.Op Fl F Ar sshconfig_file
.Op Fl f Ar routes_file
.Op Fl x Ar label_pattern
.Ar hostname ...
.Sh DESCRIPTION
.Nm
evaluates script fragments written in Progressive Label Notation
.Pq Xr pln 5 ,
executing each script in sequence using ssh connection multiplexing.
.Nm
accepts one or more hostnames which match the labels in
.Ar routes_file .
.Pp
The arguments are as follows:
.Bl -tag -width Ds
.It Fl e
Stop executing if an error is encountered within a label.
.It Fl l
List the options associated with each label.
.It Fl n
Do not connect to remote hosts.
Special text defined between { and } is still executed locally.
Hostnames are highlighted to show what characters the
.Ar hostname
matched.
.It Fl t
Allow TTY input by copying the content of each label to the remote host instead
of opening a pipe to the interpreter.
.It Fl v
Print the HTTP log messages after each label is executed.
.It Fl F
Specify a
.Pa config
file for
.Xr ssh 1
to use.
.It Fl f
Specify a
.Ar routes_file .
This file is composed of labels which correspond to
hostnames or IP addresses which are matched against
.Ar hostname .
The default is
.Pa routes.pln .
.It Fl x
Execute labels matching the specified regex.
By default only labels beginning with [0-9a-z] are evaluated.
.El
.Sh FILES
Available hosts and the pathnames to labeled scripts to run are read from
.Pa routes.pln ,
located in the current directory.
.Pp
A ssh master is established at the beginning of a session and all subsequent
interactions with a host are run over a socket at
.Pa /tmp/rset_control_{hostname} .
.Pp
The local directory
.Pa _rutils
is created if it does not exist, and is shipped to the remote host at the
beginning of each execution to directory named
.Pa /tmp/rset_staging_{http_port} .
.Sh OPTIONS
The following options are recognized when parsing a
.Xr pln 5
file:
.Ss \&environment=
Space separated list of environment variables.
Only values matching the pattern
.Ql key="value"
are added to the environment on the remote host.
.Ss \&environment_file=
Path to a file which defines environment variables validated by
.Xr renv 1 .
.Ss \&interpreter=
The interpreter to run a script fragment with.
Defaults to
.Pa /bin/sh ,
but any language may be used that is capable of reading scripts over STDIN.
.Ss \&local_interpreter=
The interpreter to evaluate content that is prepended to a script
Defaults to
.Pa /bin/sh .
.Ss \&execute_with=
Command for elevating privileges, such as
.Xr doas 1
and
.Xr sudo 8 .
.Sh SEE ALSO
.Xr miniquark 1 ,
.Xr rinstall 1 ,
.Xr rsub 1 ,
.Xr ssh_config 5 ,
.Xr re_format 7
