.\"
.\" Copyright (c) 2018 Eric Radman <ericshane@eradman.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd August 27, 2018
.Dt RSET 1
.Os
.Sh NAME
.Nm rset
.Nd configure systems using labeled scripts
.Sh SYNOPSIS
.Nm rset
.Op Fl lln
.Op Fl F Ar ssh_config
.Op Fl f Ar route_file
.Ar host_regex
.Op Ar label
.Sh DESCRIPTION
.Nm
evaluates script fragments written in Progressive Label Notation
.Pq Xr pln 5 ,
executing each one in tern using ssh connection multiplexing.
.Nm
requires one parameter specifying the regular expression matching hosts
to configure.
A
.Ar label
name may be specified in order to run scripts with a specific label name.
.Pp
The arguments are as follows:
.Bl -tag -width Ds
.It Fl l
List the name of each label before execution.
Specify more than once to list options associated with each label.
.It Fl n
Do not execute commands.
Instead hostnames are highlighted to show what characters the
.Ar host_regex
matched.
.It Fl F
Specify an
.Xr ssh_config 5
file to use.
By default
.Xr ssh 1
will read
.Pa /etc/ssh/ssh_config
and
.Pa ~/.ssh/config .
.It Fl f
Specify a
.Ar route_file .
This file is composed of labels which correspond to
hostnames or IP addresses which are matched against
.Ar host_regex .
The default is
.Pa routes.pln .
.El
.Sh ENVIRONMENT
Execution on the remote host sets the following environment variables:
.Ev LABEL ,
.Ev INSTALL_URL .
.Sh FILES
Available hosts and the pathnames to labeled scripts to run are read from
.Pa routes.pln ,
located in the current directory.
.Pp
A ssh master is established at the beginning of a session and all subsequent
interactions with a host are run over a socket at
.Pa /tmp/rset_control_{hostname} .
.Pp
The local directory
.Pa _rutils
must exist, and is shipped to the remote host at the beginning of each
execution as a temporary directory named
.Pa /tmp/rset_staging_{http_port} .
This is used to set the current working directory in the environment of the
remote host, hence the capabilities of
.Nm
may easily be extend by accessing utilities at this location.
.Sh OPTIONS
.Pa Most options are not set in the command line, but are modified using key
value-pairs.
.Ss \&interpreter=
The interpreter to run a script fragment with.
Defaults to
.Pa /bin/sh ,
but any language may be used that is capable of reading scripts over STDIN.
.Ss \&execute_using=
Command for elevating privileges, such as
.Xr doas 1
and
.Xr sudo 8 .
.Sh SEE ALSO
.Xr re_format 7
