.Dd August 3, 2026
.Dt RSET 1
.Os
.Sh NAME
.Nm rset
.Nd remote staging and execution tool
.Sh SYNOPSIS
.Nm rset
.Op Fl AnRt
.Op Fl E Ar environment
.Op Fl F Ar sshconfig_file
.Op Fl f Ar routes_file
.Op Fl x Ar label_pattern
.Ar hostname ...
.Nm rset
.Op Fl E Ar environment
.Op Fl F Ar sshconfig_file
.Op Fl f Ar routes_file
.Op Fl x Ar label_pattern
.Fl o Ar log_directory
.Fl p Ar workers
.Ar hostname ...
.Nm rset
.Ar command
.Sh DESCRIPTION
.Nm
evaluates script fragments written in Progressive Label Notation
.Pq Xr pln 5 ,
executing each script in sequence using ssh connection multiplexing.
.Pp
.Nm
expects one or more hostnames matching labels in the
.Ar routes_file .
If arguments contain characters consistent with a valid network address, they
are compared with all host aliases, otherwise they are treated as regular
expressions.
.Ss Arguments
.Bl -tag -width Ds
.It Fl A
Download files listed in label export paths to the local
.Pa _archive
directory in the format
.Sq hostname:basename(filename) .
Absolute paths are permitted, or paths relative to the staging directory.
.It Fl E Ar environment
Set one or more environment variables using the format
.Sq name="value" ... .
.It Fl F Ar sshconfig_file
Specify a
.Pa config
file for
.Xr ssh 1
to use.
.It Fl f Ar routes_file
Specify a
.Ar routes_file .
This file is composed of labels which correspond to
hostnames or IP addresses which are matched against
.Ar hostname .
The default is
.Pa routes.pln .
.It Fl n
Do not connect to remote hosts.
May be combined with
.Fl x
to highlight label names that match.
Special text defined between { and } is still executed locally.
.It Fl o Ar log_directory
Log directory to use for background workers.
Each log file is created for each worker using the format
.Ql YYYY-MM-DD_HHMMSS.n .
.It Fl p Ar workers
Parallel execution distributed across the specified number of workers.
The log directory must also be specified using
.Fl o .
A summary of results is displayed using the
.Pa rexec-summary
script located in the search path.
.It Fl R
Send files listed in label export paths from the local
.Pa _archive
directory.
This is the reverse of
.Fl A .
.It Fl t
Allow TTY input by copying the content of each label to the remote host instead
of opening a pipe to the interpreter.
.It Fl x Ar label_pattern
Execute labels matching the specified regex.
By default only labels beginning with [0-9a-z] are evaluated.
.El
.Ss Commands
.Bl -tag -width Ds
.It Cm shell-env
Print environment used by parallel execution.
Provides a configuration template for custom status messages.
.El
.Sh ENVIRONMENT
.Ss Status Format
Status messages for each stage of execution may be customized by setting
.Ev RSET_HOST_CONNECT ,
.Ev RSET_HOST_CONNECT_ERROR ,
.Ev RSET_LABEL_EXEC_BEGIN ,
.Ev RSET_LABEL_EXEC_END ,
.Ev RSET_LABEL_EXEC_ERROR ,
and
.Ev RSET_HOST_DISCONNECT .
.Pp
Setting
.Ev RSET_HOST_CONNECT
disables the default status messages and is the only required variable.
These have no effect in conjunction with the
.Fl n
flag.
The following variables are interpolated:
.Pp
.Bl -tag -compact -width 4n
.It Li \%%e
exit code
.It Li \%%l
label name
.It Li \%%h
hostname
.It Li \%%s
session identifier
.It Li \%%T
rfc-3339 timestamp
.It Li \%%%
literal
.Ql %
.El
.Ss Diagnostics
.Bl -tag -width "RSET_ENVIRONMENT"
.It Ev HTTP_TRACE
If defined, print log messages from
.Xr miniquark 1 .
.It Ev SSH_TRACE
If defined, print commands used for remote execution.
.El
.Ss Remote Execution
The following environment variables are set on the remote host:
.Bl -tag -width "RSET_ENVIRONENT"
.It Ev INSTALL_URL
Used by
.Xr rinstall 1
for fetching content from
.Pa _sources .
.It Ev SD
Staging directory where
.Nm
unpacks utilities and configuration files.
.El
.Pp
State may set for the duration of the ssh session using
.Xr renv 1
using
.Ql name=value
as the first argument.
.Sh OPTIONS
The following options are recognized when parsing a
.Xr pln 5
file:
.Bl -tag -width Ds
.It Dv environment=
Space separated list of environment variables validated by
.Xr renv 1 .
.It Dv environment_file=
Space separated list of files defining environment variables validated by
.Xr renv 1 .
.It Dv interpreter=
The interpreter used to run scripts on the remote host.
Default is
.Pa /bin/sh .
.It Dv local_interpreter=
The interpreter to evaluate content that is prepended to a script
Default is
.Pa /bin/sh .
.It Dv execute_with=
Command for elevating privileges, such as
.Xr doas 1
and
.Xr sudo 8 .
.El
.Sh SEE ALSO
.Xr rinstall 1 ,
.Xr rsub 1 ,
.Xr ssh_config 5 ,
.Xr re_format 7
.Sh AUTHORS
.An Eric Radman Aq Mt ericshane@eradman.com
