.\"
.\" Copyright (c) 2018 Eric Radman <ericshane@eradman.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd June 16, 2021
.Dt RSUB 1
.Os
.Sh NAME
.Nm rsub
.Nd substitute lines in a file or append if not found
.Sh SYNOPSIS
.Nm rsub
.Op Fl A
.Fl r Ar line_regex
.Fl l Ar line_text
.Ar target
.Nm rsub
.Ar target
.Ar < block_content
.Sh DESCRIPTION
.Nm
is shipped to remote machines by
.Xr rset 1
to provide a standard method of modifying configuration parameters within a
file.
Two modes of operation are supported: line substitution and block replacement.
.Pp
.Ar line replacements are defined by the flags
.Fl r
and
.Fl l ,
while the content for a text block is provided on STDIN.
.Pp
The arguments for line subsitution are as follows:
.Bl -tag -width Ds
.It Fl A
Append line if the pattern is not found.
.It Fl r
A regular expression matching the line to replace.
.It Fl l
The replacement text for a matching line.
Newlines are not permitted as part of the replacement string.
.El
.Sh ENVIRONMENT
When updating a block of text,
.Ev RSUB_START
and
.Ev RSUB_END
define the beginning and ending markers.
.Sh EXIT STATUS
The
.Nm
utility exits with one of the following values:
.Pp
.Bl -tag -width Ds -offset indent -compact
.It Li 0
Target file was updated
.It Li 1
No changes were made, or an error occurred
.It Li 2
Incorrect parameters
.It Li 3
File not found
.El
.Sh SEE ALSO
.Xr awk 1 ,
.Xr rinstall 1
