server:
	interface: 0.0.0.0
	interface: ::

	access-control: 0.0.0.0/0 allow
	access-control: ::0/0 allow

	local-zone: "lan." transparent
	local-data: "edge1.lan    A     10.10.0.8"
	local-data: "edge1.lan    AAAA  fd00:52::8"

remote-control:
	control-enable: yes
	control-interface: /var/run/unbound.sock
