#!/bin/sh

# echo command line, normalize platform-specific arguments
/usr/bin/awk 'BEGIN {
	printf "tar"
	for (i=1; i<ARGC; i++)
		if (ARGV[i] != "--no-xattrs")
			printf " " ARGV[i]
	printf "\n" }' "$@"
